# SwiftLint Configuration for Spotted
# https://github.com/realm/SwiftLint

# Paths to include/exclude from linting
included:
  - Spotted/

excluded:
  - Spotted/Resources
  - DerivedData/
  - .build/
  - Pods/
  - vendor/

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length # Many UI files have long lines
  - file_length # ViewModels can be long
  - type_body_length # Complex views can be long
  - function_body_length # UI composition functions can be long
  - cyclomatic_complexity # UI logic can be complex

# Opt-in rules
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - flatmap_over_map_reduce
  - last_where
  - reduce_into
  - unused_import
  - unused_optional_binding
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Rule configurations
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - i
    - j
    - x
    - y

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID
    - URL

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 4

# Custom rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '(?<!//\s)print\('
    message: "Use proper logging instead of print()"
    severity: warning

  force_unwrap:
    name: "Avoid Force Unwraps"
    regex: '\!\s*(?!\/\/)'
    message: "Consider using optional binding instead of force unwrapping"
    severity: warning
    excluded:
      - ".*Test.swift"

# Analyzer rules
analyzer_rules:
  - unused_import
  - unused_declaration

# Reporter type
reporter: "xcode"
